from pandas import DataFrame

def exgColumnsName(df):
    df.rename(columns={'promotion_type':'促销类型',
                       'discount_rate2':'折扣率',
                       'number_station':'进站人数',
                       'number_store': '进店人数',
                       'plant_asset': '资产类型',
                       'road_class': '道路等级',
                       'plant_stars': '油站星级',
                       'store_class': '便利店等级',
                       'building_area': '总面积',
                       'business_hall': '营业厅面积',
                       'paking_area': '停车场面积',
                       'store_area': '商店面积',
                       'plant_class_code': '油站类别',
                       'plant_location_class': '位置类别',
                       'plant_keyanliang_desc': '可研量',
                       'plant_type_desc': '油站类型',
                       'type01': '汽车服务POI数量',
                       'type02': '汽车销售POI数量',
                       'type03': '汽车维修POI数量',
                       'type05': '餐饮服务POI数量',
                       'type06': '购物服务POI数量',
                       'type07': '生活服务POI数量',
                       'type08': '体育休闲服务POI数量',
                       'type10': '住宿服务POI数量',
                       'type11': '风景名胜POI数量',
                       'type12': '商务住宅POI数量',
                       'type13': '政府机构及社会团体POI数量',
                       'type14': '科教文化服务POI数量',
                       'type15': '交通设施服务POI数量',
                       'type16': '金融保险服务POI数量',
                       'type17': '公司企业POI数量',
                       'type19': '地名地址信息POI数量',
                       'type20': '公共设施POI数量',
                       'type97': '室内设施POI数量'
                       },inplace=True)
    return df

def exgColumnsName2(df):
    df.rename(columns={#'number_station':'进站人数',
                       #'number_store': '进店人数',
                       'plant_asset': '资产类型',
                       'road_class': '道路等级',
                       'plant_stars': '油站星级',
                       'store_class': '便利店等级',
                       'building_area': '总面积',
                       'business_hall': '营业厅面积',
                       'paking_area': '停车场面积',
                       'store_area': '商店面积',
                       'plant_class_code': '油站类别',
                       'plant_location_class': '位置类别',
                       'plant_keyanliang_desc': '可研量',
                       'type01': '汽车服务POI数量',
                       'type02': '汽车销售POI数量',
                       'type03': '汽车维修POI数量',
                       'type05': '餐饮服务POI数量',
                       'type06': '购物服务POI数量',
                       'type07': '生活服务POI数量',
                       'type08': '体育休闲服务POI数量',
                       'type10': '住宿服务POI数量',
                       'type11': '风景名胜POI数量',
                       'type12': '商务住宅POI数量',
                       'type13': '政府机构及社会团体POI数量',
                       'type14': '科教文化服务POI数量',
                       'type15': '交通设施服务POI数量',
                       'type16': '金融保险服务POI数量',
                       'type17': '公司企业POI数量',
                       'type19': '地名地址信息POI数量',
                       'type20': '公共设施POI数量',
                       'type97': '室内设施POI数量'
                       },inplace=True)
    return df