from pandas import DataFrame

def exgColumnsName(df):

    df.rename(columns={
        'material': '品牌',
                        'promotion_type':'促销类型',
        'promotion_type_C': '促销类型-C',
        'promotion_type_O': '降价促销-直接降价',
        'promotion_type_P': '降价促销-百分比折扣',
        'promotion_type_A': '降价促销-绝对值折扣',
        'promotion_type_BB05': '整额折扣-百分比折扣',
        'promotion_type_NP': '无促销活动',
        'promotion_type_G': '促销类型-G',
                       'discount_rate2':'折扣率',
                       'number_station':'进站人数',
                       'number_store':'进店人数',
                       'plant_asset': '资产类型',
                       'road_class': '道路等级',
                       'road_class_0001': '道路等级_快速路',
                       'road_class_0002': '道路等级_主干路',
                       'road_class_0003': '道路等级_次干路',
                       'road_class_0004': '道路等级_支路',
                       'plant_stars': '加油站星级',
                       'store_class': '便利店等级',
                       'store_class_desc': '便利店类型',
                        'store_class_desc_标准店': '标准店',
                        'store_class_desc_机油店': '机油店',
                        'store_class_desc_高级店': '高级店',
                       'building_area': '总面积',
                       'business_hall': '营业厅面积',
                       'paking_area': '停车场面积',
                       'store_area': '商店面积',
                       'plant_class_code': '油站类别',
                       'plant_class_code_0001': '一类站',
                       'plant_class_code_0002': '二类站',
                       'plant_class_code_0003': '三类站',
                       'plant_class_code_0004': '四类站',
                       # 'plant_location_class': '位置类别',
                       'plant_location_class': '加油站位置',
                       'plant_location_class_001': '位置_省会(直辖市)市区',
                       'plant_location_class_002': '位置类别_地级市市区',
                       'plant_location_class_003': '位置类别_高速公路',
                       'plant_location_class_004': '位置类别_环城快速路',
                       'plant_location_class_005': '位置类别_城郊结合部',
                       'plant_location_class_006': '位置类别_县级市市区',
                       'plant_location_class_007': '位置类别_县城城区',
                       'plant_location_class_008': '位置类别_国道',
                       'plant_location_class_009': '位置类别_省道',
                       'plant_location_class_010': '位置类别_县乡道路',
                       'plant_location_class_011': '位置类别_乡镇',
                       'plant_keyanliang_desc': '可研量',
                       'plant_type_desc': '油站类型',
                       # 'type01': '汽车服务POI数量',
                       # 'type02': '汽车销售POI数量',
                       # 'type03': '汽车维修POI数量',
                       'type05': '餐饮服务POI数量',
                       'type06': '购物服务POI数量',
                       'type07': '生活服务POI数量',
                       'type08': '体育休闲服务POI数量',
                       'type10': '住宿服务POI数量',
                       # 'type11': '风景名胜POI数量',
                       'type12': '商务住宅POI数量',
                       # 'type13': '政府机构及社会团体POI数量',
                       'type14': '科教文化服务POI数量',
                       # 'type15': '交通设施服务POI数量',
                       # 'type16': '金融保险服务POI数量',
                       'type17': '公司企业POI数量',
                       'plant_asset_0001': '资产类型_全资',
                       'plant_asset_0002': '资产类型_控股',
                       'plant_asset_0003': '资产类型_长租',
                       'plant_asset_0004': '资产类型_短租',
                       'plant_asset_0005': '资产类型_电销',
                       # 'type19': '地名地址信息POI数量',
                       # 'type20': '公共设施POI数量',
                       # 'type97': '室内设施POI数量'
                        'weekday': '星期',
                        'is_holiday': '节假日',
                        'month':'月份'

                       }, inplace=True)
    return df

def exgColumnsName2(df):
    df.rename(columns={#'number_station':'进站人数',
                       #'number_store': '进店人数',
                       'plant_asset': '资产类型',
                       'road_class': '道路等级',
                       'plant_stars': '油站星级',
                       'store_class': '便利店等级',
                       'store_class_desc': '便利店类型',
                       'building_area': '总面积',
                       'business_hall': '营业厅面积',
                       'paking_area': '停车场面积',
                       'store_area': '商店面积',
                       'plant_class_code': '油站类别',
                       'plant_location_class': '位置类别',
                       'plant_keyanliang_desc': '可研量',
                       'type01': '汽车服务POI数量',
                       'type02': '汽车销售POI数量',
                       'type03': '汽车维修POI数量',
                       'type05': '餐饮服务POI数量',
                       'type06': '购物服务POI数量',
                       'type07': '生活服务POI数量',
                       'type08': '体育休闲服务POI数量',
                       'type10': '住宿服务POI数量',
                       'type11': '风景名胜POI数量',
                       'type12': '商务住宅POI数量',
                       'type13': '政府机构及社会团体POI数量',
                       'type14': '科教文化服务POI数量',
                       'type15': '交通设施服务POI数量',
                       'type16': '金融保险服务POI数量',
                       'type17': '公司企业POI数量',
                       'type19': '地名地址信息POI数量',
                       'type20': '公共设施POI数量',
                       'type97': '室内设施POI数量'
                       },inplace=True)
    return df